services:
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   volumes:
  #     - ./zookeeper/data:/var/lib/zookeeper/data
  #     - ./zookeeper/datalog:/var/lib/zookeeper/log
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - 2181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    # depends_on:
    #   - zookeeper
    ports:
      # - 9092:9092
      - 9094:9094
      # - 29093:29093
    environment:
      KAFKA_BROKER_ID: 3
      # KAFKA_ZOOKEEPER_CONNECT: zookeper:2181
      KAFKA_ZOOKEEPER_CONNECT: 192.168.137.1:2181
      KAFKA_LISTENERS: INTERNAL://:19094,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19094,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
      # KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      
    
  
  # kafdrop:
  #   image: obsidiandynamics/kafdrop
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     KAFKA_BROKERCONNECT: "kafka:19094"
  #   depends_on:
  #     - kafka